In [1]:
import sys
sys.path.append('..')
from epicast.utils import *
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

In [2]:
metadata = pd.read_csv('../data/AlphaGenome/AlphaGenome_metadata.csv')
metadata

                     name strand Assay title ontology_curie                      biosample_name                 biosample_type biosample_life_stage data_source endedness genetically_modified        output_type gtex_tissue histone_mark transcription_factor
0     CL:0000084 ATAC-seq      .    ATAC-seq     CL:0000084                              T-cell                   primary_cell                adult      encode    paired                False    OutputType.ATAC         NaN          NaN                  NaN
1     CL:0000100 ATAC-seq      .    ATAC-seq     CL:0000100                        motor neuron  in_vitro_differentiated_cells                adult      encode    paired                False    OutputType.ATAC         NaN          NaN                  NaN
2     CL:0000236 ATAC-seq      .    ATAC-seq     CL:0000236                              B cell                   primary_cell                adult      encode    paired                False    OutputType.ATAC         NaN          NaN                  NaN
3     CL:0000623 ATAC-seq      .    ATAC-seq     CL:0000623                 natural killer cell                   primary_cell                adult      encode    paired                False    OutputType.ATAC         NaN          NaN                  NaN
4     CL:0000624 ATAC-seq      .    ATAC-seq     CL:0000624     CD4-positive, alpha-beta T cell                   primary_cell                adult      encode    paired                False    OutputType.ATAC         NaN          NaN                  NaN
...                   ...    ...         ...            ...                                 ...                            ...                  ...         ...       ...                  ...                ...         ...          ...                  ...
5558          ENCSR182QNJ      -     PRO-cap    EFO:0001099                              Caco-2                      cell_line                  NaN      encode       NaN                False  OutputType.PROCAP         NaN          NaN                  NaN
5559          ENCSR740IPL      -     PRO-cap    EFO:0002067                                K562                      cell_line                  NaN      encode       NaN                False  OutputType.PROCAP         NaN          NaN                  NaN
5560          ENCSR797DEF      -     PRO-cap    EFO:0002819                               Calu3                      cell_line                  NaN      encode       NaN                False  OutputType.PROCAP         NaN          NaN                  NaN
5561          ENCSR801ECP      -     PRO-cap     CL:0002618  endothelial cell of umbilical vein                   primary_cell                  NaN      encode       NaN                False  OutputType.PROCAP         NaN          NaN                  NaN
5562          ENCSR860TYZ      -     PRO-cap    EFO:0001200                             MCF 10A                      cell_line                  NaN      encode       NaN                False  OutputType.PROCAP         NaN          NaN                  NaN

[5563 rows x 14 columns]

In [3]:
metadata['Assay title'].value_counts()

Assay title
TF ChIP-seq           1617
Histone ChIP-seq      1116
total RNA-seq          784
polyA plus RNA-seq     617
hCAGE                  516
DNase-seq              305
ATAC-seq               167
LQhCAGE                 30
in situ Hi-C            24
PRO-cap                 12
Micro-C                  3
Dilution Hi-C            1
Name: count, dtype: int64

In [4]:
metadata['cell_type'] = metadata['biosample_name']
metadata['assay'] = metadata['Assay title']

mask = (metadata['Assay title'] == 'DNase-seq')
metadata.loc[mask, 'assay'] = 'DNase'
mask = (metadata['Assay title'] == 'TF ChIP-seq')
metadata.loc[mask, 'assay'] = metadata.loc[mask, 'transcription_factor']
mask = (metadata['Assay title'] == 'Histone ChIP-seq')
metadata.loc[mask, 'assay'] = metadata.loc[mask, 'histone_mark']

metadata['index'] = metadata.index

In [5]:
df_pivot = metadata.pivot_table(
    values="index", 
    index="cell_type", 
    columns="assay", 
    aggfunc=list,
)

df_pivot

assay                           ADNP AFF1 AFF4 AGO1 AGO2 AHDC1  AHR AKAP8 ARHGAP35 ARID1B ARID2 ARID3A ARID4A ARID4B ARID5B ARNT ARNT2 ARNTL ASH1L ASH2L ATAC-seq ATF1 ATF2 ATF3 ATF4 ATF7 ATF7-NPFF BACH1 BATF BATF2 BAZ2A BCL11A BCL11B    BCL3 BCL6 BCLAF1 BCOR BHLHE40 BMI1 BORCS8-MEF2B BRCA1 BRD4 BRD9 BRF2 C11orf30 CAMTA2 CBFA2T2 CBFA2T3 CBFB CBX1  ... ZNF710 ZNF724P ZNF740 ZNF746 ZNF747 ZNF749 ZNF76 ZNF761 ZNF766 ZNF768 ZNF770 ZNF772 ZNF776 ZNF777 ZNF778 ZNF780A ZNF782 ZNF784 ZNF786 ZNF788 ZNF790 ZNF792 ZNF800 ZNF816 ZNF827 ZNF83 ZNF839 ZNF843 ZNF865 ZNF878 ZNF879 ZNF891 ZSCAN20 ZSCAN21 ZSCAN22 ZSCAN25 ZSCAN29 ZSCAN30 ZSCAN31 ZSCAN4 ZSCAN5A ZSCAN5C ZSCAN9 ZXDB ZXDC ZZZ3       hCAGE in situ Hi-C        polyA plus RNA-seq             total RNA-seq
cell_type                                                                                                                                                                                                                                                                                                                                                    ...
22Rv1                            NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN         NaN          NaN                       NaN                       NaN
A172                             NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [319, 592]          NaN                       NaN  [1140, 1411, 4564, 4931]
A375                             NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN         NaN          NaN                       NaN  [1141, 1412, 4565, 4932]
A549                             NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN     [55]  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN  [2868]  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [311, 584]          NaN  [1125, 1396, 4548, 4915]                       NaN
A673                             NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN         NaN          NaN                       NaN  [1142, 1413, 4566, 4933]
...                              ...  ...  ...  ...  ...   ...  ...   ...      ...    ...   ...    ...    ...    ...    ...  ...   ...   ...   ...   ...      ...  ...  ...  ...  ...  ...       ...   ...  ...   ...   ...    ...    ...     ...  ...    ...  ...     ...  ...          ...   ...  ...  ...  ...      ...    ...     ...     ...  ...  ...  ...    ...     ...    ...    ...    ...    ...   ...    ...    ...    ...    ...    ...    ...    ...    ...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   ...    ...    ...    ...    ...    ...    ...     ...     ...     ...     ...     ...     ...     ...    ...     ...     ...    ...  ...  ...  ...         ...          ...                       ...                       ...
vermiform appendix               NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [362, 635]          NaN                       NaN                       NaN
vertebral mesenchymal stem cell  NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [267, 540]          NaN                       NaN                       NaN
visceral preadipocyte            NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [276, 549]          NaN                       NaN                       NaN
vitreous humor                   NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [375, 648]          NaN                       NaN                       NaN
zone of skin                     NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN      NaN    NaN   NaN    NaN    NaN    NaN    NaN  NaN   NaN   NaN   NaN   NaN      NaN  NaN  NaN  NaN  NaN  NaN       NaN   NaN  NaN   NaN   NaN    NaN    NaN     NaN  NaN    NaN  NaN     NaN  NaN          NaN   NaN  NaN  NaN  NaN      NaN    NaN     NaN     NaN  NaN  NaN  ...    NaN     NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN    NaN  NaN  NaN  NaN  [332, 605]          NaN                       NaN                       NaN

[714 rows x 790 columns]

In [6]:
assays = ['DNase', 'H3K4me3', 'H3K27ac', 'CTCF']
df_pivot.loc[df_pivot[assays].notna().all(axis=1), assays]

assay                                  DNase H3K4me3 H3K27ac                                               CTCF
cell_type
A549                                   [820]  [2016]  [2013]                                             [2870]
A673                                   [835]  [2098]  [2096]                                             [3951]
AG04450                                [897]  [2274]  [2272]                                             [4260]
B cell                                 [724]  [1782]  [1777]                                             [2810]
CD14-positive monocyte                 [756]  [1886]  [1881]                                             [2826]
CD4-positive, alpha-beta T cell        [731]  [1835]  [1831]                                             [2815]
CD8-positive, alpha-beta T cell        [732]  [1841]  [1837]                                             [2816]
DND-41                                 [900]  [2309]  [2305]                                             [4265]
GM12878                                [850]  [2135]  [2131]                                             [3981]
GM23338                                [909]  [2390]  [2385]                                             [4270]
H1                                     [863]  [2183]  [2178]                                             [4161]
HCT116                                 [859]  [2155]  [2150]  [4128, 4129, 4130, 4131, 4132, 4133, 4134, 413...
HL-60                                  [856]  [2148]  [2147]                                             [4117]
HeLa-S3                                [855]  [2144]  [2139]                                             [4081]
HepG2                                  [822]  [2028]  [2023]                                       [3065, 3066]
IMR-90                                 [824]  [2049]  [2043]                                             [3558]
K562                                   [831]  [2082]  [2077]                                             [3689]
MCF-7                                  [826]  [2064]  [2060]                                             [3577]
MM.1S                                  [890]  [2254]  [2250]                                             [4255]
OCI-LY7                                [899]  [2295]  [2291]                                             [4264]
PC-3                                   [832]  [2092]  [2087]                                             [3949]
PC-9                                   [860]  [2164]  [2160]                                             [4151]
Panc1                                  [847]  [2124]  [2121]                                             [3955]
Peyer's patch                          [947]  [2537]  [2534]                                             [4343]
RWPE2                                  [905]  [2382]  [2380]                                             [4267]
SK-N-SH                                [866]  [2201]  [2196]                                             [4194]
WERI-Rb-1                              [884]  [2224]  [2221]                                             [4237]
adrenal gland                          [985]  [2678]  [2674]                                             [4386]
ascending aorta                        [953]  [2561]  [2558]                                             [4350]
astrocyte                              [716]  [1720]  [1715]                                             [2803]
body of pancreas                       [944]  [2519]  [2517]                                             [4333]
brain microvascular endothelial cell   [805]  [2000]  [1998]                                             [2863]
breast epithelium                     [1000]  [2747]  [2744]                                             [4402]
cardiac muscle cell                    [737]  [1849]  [1845]                                             [2823]
colonic mucosa                         [929]  [2458]  [2454]                                             [4318]
coronary artery                        [956]  [2568]  [2567]                                             [4352]
dorsolateral prefrontal cortex        [1005]  [2768]  [2764]                                             [4411]
endodermal cell                        [723]  [1774]  [1770]                                             [2809]
endothelial cell of umbilical vein     [786]  [1966]  [1961]                                             [2848]
fibroblast of dermis                   [773]  [1943]  [1939]                                             [2841]
fibroblast of lung                     [775]  [1951]  [1947]                                             [2842]
foreskin fibroblast                    [797]  [1989]  [1985]                                             [2862]
foreskin keratinocyte                  [796]  [1982]  [1978]                                             [2861]
gastrocnemius medialis                [1007]  [2774]  [2770]                                             [4413]
heart left ventricle                   [970]  [2621]  [2617]                                             [4357]
heart right ventricle                  [969]  [2615]  [2611]                                             [4356]
keratinocyte                           [725]  [1791]  [1787]                                             [2811]
left lung                              [978]  [2650]  [2646]                                             [4380]
left ventricle myocardium inferior     [917]  [2412]  [2408]                                             [4315]
liver                                  [973]  [2632]  [2629]                                             [4363]
lower lobe of left lung               [1003]  [2762]  [2758]                                             [4410]
lower lobe of right lung               [980]  [2660]  [2656]                                             [4382]
mammary epithelial cell                [764]  [1920]  [1915]                                             [2834]
natural killer cell                    [730]  [1829]  [1826]                                             [2814]
neural progenitor cell                 [790]  [1975]  [1971]                                             [2858]
ovary                                  [939]  [2492]  [2488]                                             [4324]
pancreas                               [949]  [2544]  [2541]                                             [4345]
placenta                               [963]  [2589]  [2585]                                             [4353]
prostate gland                         [984]  [2673]  [2671]                                             [4383]
psoas muscle                          [1001]  [2753]  [2749]                                             [4405]
right atrium auricular region          [998]  [2729]  [2726]                                             [4398]
right lobe of liver                    [942]  [2510]  [2507]                                             [4331]
sigmoid colon                          [946]  [2529]  [2525]                                             [4339]
skeletal muscle myoblast               [727]  [1812]  [1809]                                             [2813]
spleen                                 [972]  [2627]  [2623]                                             [4359]
stomach                                [931]  [2474]  [2470]                                             [4320]
suprapubic skin                       [1013]  [2800]  [2796]                                             [4415]
testis                                 [930]  [2469]  [2467]                                             [4319]
thoracic aorta                         [955]  [2566]  [2563]                                             [4351]
thyroid gland                          [965]  [2600]  [2597]                                             [4354]
tibial artery                          [999]  [2742]  [2738]                                             [4401]
tibial nerve                           [951]  [2550]  [2546]                                             [4347]
transverse colon                       [945]  [2524]  [2520]                                             [4335]
upper lobe of left lung               [1002]  [2757]  [2754]                                             [4406]
upper lobe of right lung               [979]  [2655]  [2652]                                             [4381]
uterus                                 [940]  [2495]  [2494]                                             [4326]

In [7]:
cell_types = ['HEK293T', 'HeLa-S3', 'HepG2', 'HL-60', 'Jurkat', 'K562', 'MCF-7', 'PANC-1', 'Raji']
cell_names = ['HEK293T', 'HeLa-S3', 'HepG2', 'HL-60', 'Jurkat', 'K562', 'MCF-7', 'Panc1', 'Raji', 'DND-41', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'GM12878','B cell']

assays = ['DNase', 'H3K4me3', 'H3K27ac', 'CTCF']

df_track = df_pivot.loc[cell_names, assays]
df_track

assay                            DNase H3K4me3 H3K27ac          CTCF
cell_type
HEK293T                            NaN     NaN     NaN           NaN
HeLa-S3                          [855]  [2144]  [2139]        [4081]
HepG2                            [822]  [2028]  [2023]  [3065, 3066]
HL-60                            [856]  [2148]  [2147]        [4117]
Jurkat                             NaN     NaN     NaN           NaN
K562                             [831]  [2082]  [2077]        [3689]
MCF-7                            [826]  [2064]  [2060]        [3577]
Panc1                            [847]  [2124]  [2121]        [3955]
Raji                               NaN     NaN     NaN           NaN
DND-41                           [900]  [2309]  [2305]        [4265]
CD4-positive, alpha-beta T cell  [731]  [1835]  [1831]        [2815]
CD8-positive, alpha-beta T cell  [732]  [1841]  [1837]        [2816]
GM12878                          [850]  [2135]  [2131]        [3981]
B cell                           [724]  [1782]  [1777]        [2810]

In [8]:
pred_DNase = load_h5('../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_DNase.h5')
print(pred_DNase.shape)

pred_Histone = load_h5('../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_Histone.h5')
print(pred_Histone.shape)

pred_TF = load_h5('../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_TF.h5')
print(pred_TF.shape)

file ../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_DNase.h5 has keys: ['data']
(18000, 305)
file ../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_Histone.h5 has keys: ['data']
(18000, 1116)
file ../predict_CRE_activity/outputs/TFBU_MPRA_18000_AlphaGenome_pred_TF.h5 has keys: ['data']
(18000, 1617)

In [9]:
MPRA_df = pd.read_csv('../data/TFBU_9cell/data.tsv', sep='\t')
MPRA_df.describe()

        HEK293T   HeLa-S3     HepG2     HL-60    Jurkat      K562     MCF-7    PANC-1      Raji
count 16942.000 16795.000 16911.000 16778.000 16842.000 16782.000 16951.000 16949.000 16827.000
mean     -1.168    -0.631    -0.730    -0.346    -1.037    -1.764    -0.009    -0.872    -0.872
std       1.262     0.775     1.156     0.681     1.383     1.868     0.488     0.932     1.317
min      -3.813    -2.904    -2.580    -2.581    -4.374    -6.029    -1.848    -3.058    -4.459
25%      -2.003    -1.106    -1.562    -0.696    -2.049    -3.163    -0.268    -1.529    -1.895
50%      -1.615    -0.843    -1.144    -0.510    -1.399    -2.222    -0.137    -1.128    -1.170
75%      -0.793    -0.406    -0.230    -0.255    -0.292    -0.700     0.069    -0.451    -0.064
max       8.135     9.766     5.756     4.982     4.781     5.265     7.016     9.230     5.413

In [10]:
notna_indice = MPRA_df[MPRA_df[cell_types].notna().all(axis=1)].index
MPRA_df = MPRA_df.loc[notna_indice]

In [11]:
data = MPRA_df.drop(columns=['id', 'seq'])
data = (data - data.mean(axis=0)) / data.std(axis=0)
data.describe()

        HEK293T   HeLa-S3     HepG2     HL-60    Jurkat      K562     MCF-7    PANC-1      Raji
count 16633.000 16633.000 16633.000 16633.000 16633.000 16633.000 16633.000 16633.000 16633.000
mean     -0.000     0.000     0.000    -0.000     0.000    -0.000     0.000    -0.000     0.000
std       1.000     1.000     1.000     1.000     1.000     1.000     1.000     1.000     1.000
min      -1.388    -2.940    -1.598    -3.289    -2.418    -2.279    -1.880    -2.096    -2.297
25%      -0.666    -0.616    -0.719    -0.517    -0.733    -0.749    -0.541    -0.708    -0.778
50%      -0.356    -0.277    -0.359    -0.244    -0.264    -0.247    -0.273    -0.276    -0.228
75%       0.298     0.288     0.430     0.131     0.537     0.570     0.149     0.452     0.613
max       7.347    13.422     5.593     7.830     4.203     3.758    14.464    10.823     4.770

In [12]:
mean = data.mean(axis=1)  # 每条序列跨细胞均值（忽略 NaN）
for cell_type in cell_types:
    diff = (data[cell_type] - mean).abs()
    thr = diff.quantile(0.8)
    mask = (diff >= thr)
    data[f"{cell_type}_specific"] = mask

In [13]:
VEF_df = pd.DataFrame()

for i, cell_name in enumerate(cell_names):
    for j, assay in enumerate(assays):
        indice = df_track.loc[cell_name, assay]
        if isinstance(indice, list) and len(indice) > 0:
            if assay == 'DNase':
                indice = [i-713 for i in indice]
                pred_array = pred_DNase
            elif assay in ['H3K4me3', 'H3K27ac']:
                indice = [i-1685 for i in indice]
                pred_array = pred_Histone
            elif assay == 'CTCF':
                indice = [i-2803 for i in indice]
                pred_array = pred_TF
            else:
                VEF_df[f'{cell_name}_{assay}'] = np.nan
                continue
            pred = pred_array[:, indice].mean(1)
            VEF_df[f'{cell_name}_{assay}'] = pred
        else:
            VEF_df[f'{cell_name}_{assay}'] = np.nan

VEF_df.describe()

,HEK293T_DNase,HEK293T_H3K4me3,HEK293T_H3K27ac,HEK293T_CTCF,HeLa-S3_DNase,HeLa-S3_H3K4me3,HeLa-S3_H3K27ac,HeLa-S3_CTCF,HepG2_DNase,HepG2_H3K4me3,HepG2_H3K27ac,HepG2_CTCF,HL-60_DNase,HL-60_H3K4me3,HL-60_H3K27ac,HL-60_CTCF,Jurkat_DNase,Jurkat_H3K4me3,Jurkat_H3K27ac,Jurkat_CTCF,K562_DNase,K562_H3K4me3,K562_H3K27ac,K562_CTCF,MCF-7_DNase,MCF-7_H3K4me3,MCF-7_H3K27ac,MCF-7_CTCF,Panc1_DNase,Panc1_H3K4me3,Panc1_H3K27ac,Panc1_CTCF,Raji_DNase,Raji_H3K4me3,Raji_H3K27ac,Raji_CTCF,DND-41_DNase,DND-41_H3K4me3,DND-41_H3K27ac,DND-41_CTCF,"CD4-positive, alpha-beta T cell_DNase","CD4-positive, alpha-beta T cell_H3K4me3","CD4-positive, alpha-beta T cell_H3K27ac","CD4-positive, alpha-beta T cell_CTCF","CD8-positive, alpha-beta T cell_DNase","CD8-positive, alpha-beta T cell_H3K4me3","CD8-positive, alpha-beta T cell_H3K27ac","CD8-positive, alpha-beta T cell_CTCF",GM12878_DNase,GM12878_H3K4me3,GM12878_H3K27ac,GM12878_CTCF,B cell_DNase,B cell_H3K4me3,B cell_H3K27ac,B cell_CTCF
count,0.000,0.000,0.000,0.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,0.000,0.000,0.000,0.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,0.000,0.000,0.000,0.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000,18000.000
mean,NaN,NaN,NaN,NaN,0.191,22.136,60.815,136.124,0.150,15.585,42.799,29.125,0.213,17.686,14.388,31.046,NaN,NaN,NaN,NaN,0.251,30.025,40.703,67.514,0.195,26.021,24.688,110.277,0.222,41.398,37.718,5.349,NaN,NaN,NaN,NaN,0.215,24.539,29.089,8.426,0.212,21.576,29.693,8.626,0.188,19.797,46.181,10.682,0.135,15.859,25.847,35.005,0.140,17.096,33.533,10.332
std,NaN,NaN,NaN,NaN,0.510,50.400,182.706,903.180,0.383,33.749,162.808,78.164,0.481,44.630,44.797,71.176,NaN,NaN,NaN,NaN,0.607,63.116,108.728,257.578,0.446,59.987,65.259,1043.465,0.505,141.431,115.435,9.720,NaN,NaN,NaN,NaN,0.645,73.699,121.984,18.801,0.668,90.786,82.007,31.167,0.578,69.372,159.225,13.689,0.346,34.062,116.031,115.853,0.428,45.431,109.414,10.306
min,NaN,NaN,NaN,NaN,0.002,0.473,0.441,0.544,0.003,0.795,0.485,0.513,0.003,0.740,0.204,0.621,NaN,NaN,NaN,NaN,0.003,0.834,0.684,0.969,0.003,0.809,0.396,0.288,0.002,0.540,0.315,0.631,NaN,NaN,NaN,NaN,0.000,0.830,0.396,0.479,0.001,0.407,0.773,0.304,0.001,0.537,0.582,1.006,0.002,0.646,0.220,0.680,0.002,0.580,0.555,0.885
25%,NaN,NaN,NaN,NaN,0.014,3.750,4.062,2.516,0.016,3.547,2.969,2.984,0.029,3.211,1.539,5.688,NaN,NaN,NaN,NaN,0.018,4.250,3.812,5.344,0.022,3.891,3.070,1.820,0.026,3.359,2.375,2.086,NaN,NaN,NaN,NaN,0.025,5.125,2.789,2.820,0.017,3.094,5.047,2.336,0.017,3.797,4.344,4.594,0.016,3.523,1.582,3.812,0.012,3.547,3.656,3.945
50%,NaN,NaN,NaN,NaN,0.028,6.617,7.578,4.703,0.031,5.969,5.094,5.359,0.056,5.812,2.695,10.203,NaN,NaN,NaN,NaN,0.043,8.234,7.125,10.344,0.042,7.156,5.094,3.305,0.051,6.594,4.500,3.234,NaN,NaN,NaN,NaN,0.048,8.375,4.500,4.242,0.035,4.938,7.938,3.680,0.034,5.938,6.844,6.750,0.029,5.625,2.383,6.750,0.023,5.719,5.672,6.375
75%,NaN,NaN,NaN,NaN,0.093,15.906,22.000,15.688,0.091,13.156,13.969,14.078,0.146,13.062,7.047,22.625,NaN,NaN,NaN,NaN,0.157,23.062,21.625,28.875,0.123,18.000,12.281,9.031,0.146,19.250,13.844,6.004,NaN,NaN,NaN,NaN,0.109,17.164,10.094,8.109,0.091,10.406,16.141,7.250,0.088,12.125,14.938,12.062,0.078,11.469,5.406,16.125,0.062,11.875,12.000,12.594
max,NaN,NaN,NaN,NaN,8.332,958.000,3584.000,24448.000,6.995,866.000,3976.000,1143.000,6.089,1332.000,918.000,1240.000,NaN,NaN,NaN,NaN,6.526,980.000,1620.000,6816.000,5.361,972.000,990.000,68608.000,6.861,2792.000,1580.000,710.000,NaN,NaN,NaN,NaN,10.155,1568.000,2272.000,852.000,9.497,2200.000,1408.000,1860.000,8.222,1772.000,2528.000,780.000,7.229,752.000,2180.000,2272.000,5.543,1284.000,1780.000,198.500

In [14]:
VEF_df = VEF_df.loc[notna_indice]

In [15]:
DNase_cols = [f'{cell_name}_DNase' for cell_name in cell_names]
VEF_df[DNase_cols] = VEF_df[DNase_cols] * 10
other_cols = [col for col in VEF_df.columns if col not in DNase_cols]
VEF_df[other_cols] = VEF_df[other_cols] / 10

VEF_df = np.log1p(VEF_df)
VEF_df.describe()

,HEK293T_DNase,HEK293T_H3K4me3,HEK293T_H3K27ac,HEK293T_CTCF,HeLa-S3_DNase,HeLa-S3_H3K4me3,HeLa-S3_H3K27ac,HeLa-S3_CTCF,HepG2_DNase,HepG2_H3K4me3,HepG2_H3K27ac,HepG2_CTCF,HL-60_DNase,HL-60_H3K4me3,HL-60_H3K27ac,HL-60_CTCF,Jurkat_DNase,Jurkat_H3K4me3,Jurkat_H3K27ac,Jurkat_CTCF,K562_DNase,K562_H3K4me3,K562_H3K27ac,K562_CTCF,MCF-7_DNase,MCF-7_H3K4me3,MCF-7_H3K27ac,MCF-7_CTCF,Panc1_DNase,Panc1_H3K4me3,Panc1_H3K27ac,Panc1_CTCF,Raji_DNase,Raji_H3K4me3,Raji_H3K27ac,Raji_CTCF,DND-41_DNase,DND-41_H3K4me3,DND-41_H3K27ac,DND-41_CTCF,"CD4-positive, alpha-beta T cell_DNase","CD4-positive, alpha-beta T cell_H3K4me3","CD4-positive, alpha-beta T cell_H3K27ac","CD4-positive, alpha-beta T cell_CTCF","CD8-positive, alpha-beta T cell_DNase","CD8-positive, alpha-beta T cell_H3K4me3","CD8-positive, alpha-beta T cell_H3K27ac","CD8-positive, alpha-beta T cell_CTCF",GM12878_DNase,GM12878_H3K4me3,GM12878_H3K27ac,GM12878_CTCF,B cell_DNase,B cell_H3K4me3,B cell_H3K27ac,B cell_CTCF
count,0.000,0.000,0.000,0.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,0.000,0.000,0.000,0.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,0.000,0.000,0.000,0.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000,16633.000
mean,NaN,NaN,NaN,NaN,0.617,0.813,1.050,0.910,0.583,0.708,0.839,0.805,0.760,0.716,0.524,0.998,NaN,NaN,NaN,NaN,0.752,0.952,0.966,1.126,0.696,0.866,0.759,0.691,0.761,0.910,0.808,0.387,NaN,NaN,NaN,NaN,0.681,0.865,0.697,0.509,0.621,0.673,0.890,0.477,0.600,0.722,0.903,0.658,0.529,0.691,0.541,0.863,0.496,0.701,0.799,0.641
std,NaN,NaN,NaN,NaN,0.774,0.709,1.064,1.187,0.677,0.581,0.948,0.843,0.737,0.640,0.662,0.765,NaN,NaN,NaN,NaN,0.842,0.808,0.932,1.015,0.743,0.762,0.785,1.038,0.768,0.921,0.948,0.280,NaN,NaN,NaN,NaN,0.744,0.669,0.796,0.395,0.777,0.683,0.764,0.424,0.740,0.640,0.926,0.373,0.634,0.603,0.813,0.851,0.676,0.616,0.850,0.388
min,NaN,NaN,NaN,NaN,0.025,0.047,0.050,0.054,0.030,0.076,0.049,0.059,0.025,0.071,0.020,0.071,NaN,NaN,NaN,NaN,0.027,0.085,0.066,0.092,0.026,0.078,0.039,0.030,0.023,0.058,0.031,0.069,NaN,NaN,NaN,NaN,0.004,0.084,0.046,0.047,0.013,0.047,0.084,0.032,0.009,0.061,0.064,0.114,0.018,0.063,0.024,0.066,0.021,0.056,0.054,0.085
25%,NaN,NaN,NaN,NaN,0.142,0.335,0.364,0.237,0.161,0.317,0.273,0.275,0.268,0.294,0.152,0.478,NaN,NaN,NaN,NaN,0.178,0.374,0.339,0.446,0.212,0.345,0.281,0.178,0.249,0.305,0.224,0.197,NaN,NaN,NaN,NaN,0.239,0.435,0.260,0.256,0.169,0.285,0.430,0.219,0.168,0.338,0.376,0.391,0.149,0.313,0.155,0.335,0.119,0.316,0.325,0.345
50%,NaN,NaN,NaN,NaN,0.269,0.536,0.597,0.403,0.295,0.491,0.433,0.454,0.471,0.482,0.252,0.737,NaN,NaN,NaN,NaN,0.378,0.637,0.570,0.743,0.375,0.568,0.433,0.304,0.440,0.536,0.395,0.292,NaN,NaN,NaN,NaN,0.409,0.635,0.388,0.367,0.315,0.418,0.607,0.326,0.310,0.487,0.543,0.532,0.265,0.464,0.225,0.536,0.220,0.470,0.467,0.512
75%,NaN,NaN,NaN,NaN,0.705,0.998,1.238,1.006,0.691,0.873,0.937,0.929,0.949,0.877,0.561,1.227,NaN,NaN,NaN,NaN,1.002,1.255,1.213,1.420,0.853,1.082,0.852,0.692,0.953,1.131,0.918,0.486,NaN,NaN,NaN,NaN,0.772,1.034,0.731,0.618,0.684,0.746,1.000,0.567,0.666,0.832,0.956,0.818,0.596,0.798,0.458,1.007,0.515,0.818,0.827,0.844
max,NaN,NaN,NaN,NaN,4.435,4.573,5.884,7.802,4.262,4.473,5.988,4.748,4.125,4.899,4.530,4.828,NaN,NaN,NaN,NaN,4.194,4.595,5.094,6.526,4.000,4.587,4.605,8.834,4.243,5.636,5.069,4.277,NaN,NaN,NaN,NaN,4.630,5.061,5.430,4.457,4.564,5.398,4.954,5.231,4.421,5.183,5.537,4.369,3.752,4.333,5.389,5.430,4.033,4.863,5.187,3.037

In [16]:
for j, assay in enumerate(assays):
    pearson_df = pd.DataFrame()
    for i, cell_type in enumerate(cell_types):
        for ii, cell_name in enumerate(cell_names):
            pred = VEF_df[f'{cell_name}_{assay}']
            true = MPRA_df[f'{cell_type}']
            r, _ = pearson(pred, true)
            pearson_df.loc[f'{cell_name}_{assay}', f'{cell_type}'] = r
    print(pearson_df)

                                       HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_DNase                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_DNase                            0.612    0.573  0.673  0.479   0.533 0.633  0.527   0.593 0.537
HepG2_DNase                              0.518    0.452  0.701  0.391   0.447 0.519  0.446   0.480 0.434
HL-60_DNase                              0.658    0.579  0.655  0.516   0.645 0.673  0.557   0.619 0.619
Jurkat_DNase                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_DNase                               0.675    0.586  0.677  0.523   0.647 0.733  0.546   0.645 0.628
MCF-7_DNase                              0.647    0.571  0.687  0.511   0.576 0.636  0.562   0.601 0.564
Panc1_DNase                              0.645    0.586  0.687  0.506   0.586 0.663  0.555   0.625 0.576
Raji_DNase                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_DNase                             0.652    0.589  0.636  0.485   0.658 0.650  0.617   0.580 0.614
CD4-positive, alpha-beta T cell_DNase    0.657    0.625  0.647  0.547   0.660 0.668  0.611   0.624 0.627
CD8-positive, alpha-beta T cell_DNase    0.665    0.623  0.646  0.552   0.665 0.672  0.610   0.629 0.632
GM12878_DNase                            0.666    0.604  0.674  0.530   0.628 0.641  0.621   0.605 0.605
B cell_DNase                             0.657    0.621  0.640  0.555   0.654 0.652  0.610   0.615 0.617
                                         HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_H3K4me3                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_H3K4me3                            0.567    0.569  0.637  0.433   0.542 0.613  0.527   0.554 0.522
HepG2_H3K4me3                              0.553    0.513  0.667  0.382   0.521 0.564  0.536   0.494 0.489
HL-60_H3K4me3                              0.578    0.532  0.600  0.412   0.589 0.618  0.538   0.539 0.555
Jurkat_H3K4me3                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_H3K4me3                               0.637    0.562  0.657  0.463   0.621 0.708  0.539   0.609 0.597
MCF-7_H3K4me3                              0.621    0.561  0.655  0.448   0.585 0.632  0.570   0.569 0.557
Panc1_H3K4me3                              0.546    0.545  0.622  0.392   0.537 0.615  0.531   0.533 0.524
Raji_H3K4me3                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_H3K4me3                             0.574    0.569  0.627  0.432   0.576 0.593  0.577   0.526 0.527
CD4-positive, alpha-beta T cell_H3K4me3    0.544    0.557  0.604  0.402   0.552 0.575  0.579   0.497 0.510
CD8-positive, alpha-beta T cell_H3K4me3    0.555    0.561  0.620  0.409   0.557 0.584  0.574   0.511 0.516
GM12878_H3K4me3                            0.602    0.587  0.662  0.446   0.566 0.594  0.607   0.551 0.555
B cell_H3K4me3                             0.589    0.583  0.636  0.451   0.587 0.608  0.580   0.548 0.544
                                         HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_H3K27ac                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_H3K27ac                            0.614    0.587  0.691  0.471   0.560 0.643  0.550   0.599 0.549
HepG2_H3K27ac                              0.454    0.388  0.672  0.295   0.374 0.446  0.421   0.386 0.360
HL-60_H3K27ac                              0.590    0.537  0.635  0.433   0.558 0.587  0.568   0.521 0.515
Jurkat_H3K27ac                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_H3K27ac                               0.599    0.547  0.675  0.445   0.560 0.676  0.519   0.575 0.540
MCF-7_H3K27ac                              0.625    0.541  0.690  0.447   0.530 0.604  0.577   0.553 0.521
Panc1_H3K27ac                              0.538    0.524  0.659  0.378   0.484 0.581  0.526   0.512 0.475
Raji_H3K27ac                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_H3K27ac                             0.531    0.527  0.596  0.378   0.533 0.545  0.574   0.458 0.481
CD4-positive, alpha-beta T cell_H3K27ac    0.622    0.613  0.671  0.508   0.606 0.625  0.611   0.575 0.566
CD8-positive, alpha-beta T cell_H3K27ac    0.614    0.616  0.662  0.503   0.608 0.620  0.622   0.565 0.566
GM12878_H3K27ac                            0.555    0.522  0.624  0.371   0.482 0.502  0.631   0.445 0.482
B cell_H3K27ac                             0.609    0.609  0.661  0.496   0.591 0.603  0.623   0.554 0.556
                                      HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_CTCF                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_CTCF                            0.473    0.489  0.559  0.395   0.387 0.460  0.400   0.474 0.390
HepG2_CTCF                              0.544    0.505  0.705  0.443   0.467 0.520  0.483   0.504 0.451
HL-60_CTCF                              0.573    0.551  0.666  0.456   0.504 0.597  0.485   0.569 0.508
Jurkat_CTCF                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_CTCF                               0.684    0.630  0.703  0.602   0.633 0.689  0.556   0.673 0.617
MCF-7_CTCF                              0.609    0.605  0.591  0.608   0.535 0.567  0.518   0.610 0.533
Panc1_CTCF                              0.555    0.507  0.603  0.416   0.507 0.560  0.491   0.510 0.497
Raji_CTCF                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_CTCF                             0.553    0.510  0.616  0.399   0.500 0.556  0.523   0.492 0.494
CD4-positive, alpha-beta T cell_CTCF    0.527    0.476  0.579  0.378   0.474 0.527  0.487   0.461 0.459
CD8-positive, alpha-beta T cell_CTCF    0.583    0.524  0.648  0.433   0.523 0.583  0.504   0.537 0.510
GM12878_CTCF                            0.688    0.653  0.696  0.593   0.631 0.660  0.620   0.651 0.620
B cell_CTCF                             0.561    0.504  0.618  0.397   0.509 0.553  0.480   0.513 0.481

In [17]:
for j, assay in enumerate(assays):
    pearson_df = pd.DataFrame()
    for i, cell_type in enumerate(cell_types):
        for ii, cell_name in enumerate(cell_names):
            pred = VEF_df[f'{cell_name}_{assay}']
            true = data[f'{cell_type}']

            indice = data[f'{cell_type}_specific']
            pred = pred.loc[indice]
            true = true.loc[indice]
            r, _ = pearson(pred, true)
            pearson_df.loc[f'{cell_name}_{assay}', f'{cell_type}'] = r
    print(pearson_df)

                                       HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_DNase                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_DNase                            0.409    0.416  0.534  0.338   0.277 0.484  0.353   0.438 0.198
HepG2_DNase                              0.327    0.288  0.590  0.276   0.215 0.382  0.328   0.284 0.052
HL-60_DNase                              0.471    0.395  0.439  0.342   0.497 0.528  0.380   0.425 0.341
Jurkat_DNase                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_DNase                               0.477    0.384  0.456  0.356   0.473 0.639  0.326   0.464 0.333
MCF-7_DNase                              0.480    0.404  0.533  0.377   0.351 0.479  0.400   0.426 0.212
Panc1_DNase                              0.447    0.428  0.536  0.356   0.365 0.529  0.379   0.459 0.249
Raji_DNase                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_DNase                             0.447    0.401  0.428  0.261   0.525 0.470  0.500   0.335 0.348
CD4-positive, alpha-beta T cell_DNase    0.439    0.469  0.422  0.370   0.515 0.504  0.456   0.425 0.361
CD8-positive, alpha-beta T cell_DNase    0.457    0.463  0.415  0.375   0.524 0.510  0.450   0.434 0.370
GM12878_DNase                            0.486    0.431  0.516  0.358   0.460 0.455  0.494   0.399 0.316
B cell_DNase                             0.456    0.468  0.421  0.394   0.517 0.477  0.455   0.419 0.342
                                         HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_H3K4me3                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_H3K4me3                            0.314    0.428  0.487  0.251   0.341 0.477  0.389   0.349 0.202
HepG2_H3K4me3                              0.353    0.349  0.558  0.183   0.346 0.424  0.466   0.257 0.167
HL-60_H3K4me3                              0.358    0.355  0.419  0.193   0.466 0.495  0.417   0.305 0.295
Jurkat_H3K4me3                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_H3K4me3                               0.434    0.373  0.459  0.259   0.458 0.623  0.367   0.399 0.304
MCF-7_H3K4me3                              0.427    0.391  0.498  0.250   0.407 0.492  0.448   0.346 0.239
Panc1_H3K4me3                              0.278    0.395  0.469  0.183   0.346 0.511  0.409   0.314 0.250
Raji_H3K4me3                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_H3K4me3                             0.327    0.410  0.486  0.225   0.425 0.435  0.481   0.283 0.218
CD4-positive, alpha-beta T cell_H3K4me3    0.281    0.401  0.472  0.182   0.402 0.431  0.485   0.252 0.217
CD8-positive, alpha-beta T cell_H3K4me3    0.293    0.402  0.491  0.191   0.404 0.439  0.475   0.269 0.214
GM12878_H3K4me3                            0.367    0.419  0.540  0.241   0.359 0.392  0.514   0.313 0.249
B cell_H3K4me3                             0.339    0.424  0.474  0.251   0.433 0.445  0.459   0.319 0.220
                                         HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_H3K27ac                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_H3K27ac                            0.397    0.432  0.564  0.300   0.341 0.494  0.395   0.422 0.213
HepG2_H3K27ac                              0.307    0.229  0.588  0.156   0.157 0.323  0.388   0.178 0.011
HL-60_H3K27ac                              0.412    0.374  0.505  0.247   0.397 0.423  0.473   0.322 0.196
Jurkat_H3K27ac                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_H3K27ac                               0.372    0.372  0.533  0.271   0.359 0.581  0.355   0.393 0.207
MCF-7_H3K27ac                              0.475    0.369  0.594  0.271   0.295 0.443  0.471   0.359 0.170
Panc1_H3K27ac                              0.295    0.375  0.556  0.185   0.253 0.457  0.425   0.321 0.148
Raji_H3K27ac                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_H3K27ac                             0.295    0.374  0.484  0.165   0.373 0.386  0.516   0.215 0.188
CD4-positive, alpha-beta T cell_H3K27ac    0.396    0.467  0.530  0.342   0.443 0.455  0.493   0.359 0.245
CD8-positive, alpha-beta T cell_H3K27ac    0.375    0.471  0.517  0.329   0.454 0.450  0.508   0.343 0.256
GM12878_H3K27ac                            0.354    0.345  0.558  0.147   0.265 0.269  0.587   0.200 0.200
B cell_H3K27ac                             0.380    0.467  0.527  0.326   0.426 0.416  0.521   0.333 0.236
                                      HEK293T  HeLa-S3  HepG2  HL-60  Jurkat  K562  MCF-7  PANC-1  Raji
HEK293T_CTCF                              NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
HeLa-S3_CTCF                            0.282    0.367  0.448  0.321   0.161 0.296  0.242   0.383 0.073
HepG2_CTCF                              0.364    0.372  0.585  0.367   0.228 0.336  0.370   0.313 0.057
HL-60_CTCF                              0.352    0.407  0.524  0.331   0.247 0.438  0.319   0.411 0.160
Jurkat_CTCF                               NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
K562_CTCF                               0.491    0.459  0.486  0.504   0.417 0.527  0.323   0.514 0.277
MCF-7_CTCF                              0.429    0.480  0.375  0.551   0.313 0.359  0.307   0.505 0.233
Panc1_CTCF                              0.386    0.376  0.479  0.266   0.311 0.388  0.368   0.304 0.189
Raji_CTCF                                 NaN      NaN    NaN    NaN     NaN   NaN    NaN     NaN   NaN
DND-41_CTCF                             0.380    0.375  0.536  0.222   0.304 0.390  0.432   0.285 0.196
CD4-positive, alpha-beta T cell_CTCF    0.371    0.343  0.503  0.213   0.291 0.369  0.397   0.263 0.163
CD8-positive, alpha-beta T cell_CTCF    0.416    0.375  0.542  0.283   0.320 0.420  0.370   0.347 0.175
GM12878_CTCF                            0.499    0.504  0.510  0.466   0.418 0.454  0.456   0.476 0.307
B cell_CTCF                             0.398    0.361  0.515  0.260   0.341 0.392  0.385   0.322 0.161

In [29]:
VEF_df.to_csv('../data/TFBU_9cell/AG_VEF_raw.tsv', sep='\t', index=False)

In [ ]:
# 每个 assay 固定 scale factor

VEF_df = pd.read_csv('../data/TFBU_MPRA/TFBU_MPRA_AG_VEF_raw.tsv', sep='\t')

cell_types = ['HepG2', 'HEK293T', 'Jurkat', 'PANC']
assays = ['DNase', 'H3K4me3', 'H3K27ac', 'CTCF']

for assay in assays:
    for cell_type in cell_types:
        if assay == 'DNase':
            scale_factor = 0.1
        else:
            scale_factor = 10
        x = VEF_df[f'{cell_type}_{assay}'].copy()
        x = np.log1p(x / scale_factor)
        VEF_df[f'{cell_type}_{assay}'] = x

VEF_df.to_csv('../data/TFBU_MPRA/TFBU_MPRA_AG_VEF_log1p_scale.tsv', sep='\t', index=False)

pearson_df = pd.DataFrame(dtype=float)
for i, cell_type in enumerate(cell_types):
    for j, assay in enumerate(assays):
        pred = VEF_df[f'{cell_type}_{assay}']
        true = MPRA_df[f'{cell_type}']
        r, _ = pearson(pred, true)
        pearson_df.loc[cell_type, assay] = r
print(pearson_df)